# Capstone 2 Sales Analysis

## Student
Sonia Tana

## Region
South

## Sales Territories
- Florida
- South Carolina

## Project Objective
This project analyzes sales performance, customer activity, and store performance across the assigned territories using Python, pandas, and data visualization techniques.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
store_sales = pd.read_csv("StoreSales.csv")

In [3]:
store_sales.head()

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [3]:
store_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

In [10]:
store_detail = pd.read_csv("StoreDetail.csv")

In [9]:
products = pd.read_csv("Products.csv")

In [7]:
product_categories = pd.read_csv("ProductCategories.csv")

In [8]:
customer_list = pd.read_csv("customer_list.csv")

In [10]:
store_sales.head()

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [11]:
store_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

In [12]:
products.head()

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [13]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

In [14]:
product_categories.head()

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [15]:
product_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

In [16]:
customer_list.head()

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

In [17]:
store_detail.head()

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [18]:
store_detail.columns

Index(['Store Location', 'State', 'Store ID', 'Territory Manager', 'Region',
       'Region Director'],
      dtype='object')

In [28]:
florida_stores = store_detail[store_detail["State"] == "Florida"]

In [24]:
florida_stores[["Store ID", "Store Location", "Territory Manager", "Region"]]

    Store ID   Store Location Territory Manager Region
26       719   Cape Canaveral        Lana Ilana  South
27       720  Fort Lauderdale        Lana Ilana  South
28       721     Jacksonville        Lana Ilana  South
29       722         Key West        Lana Ilana  South
30       723         Lakeland        Lana Ilana  South
31       724            Miami        Lana Ilana  South
32       725           Naples        Lana Ilana  South
33       726          Orlando        Lana Ilana  South
34       727          Sebring        Lana Ilana  South
35       728      Tallahassee        Lana Ilana  South
36       729            Tampa        Lana Ilana  South

In [29]:
sc_stores = store_detail[store_detail["State"] == "South Carolina"]

In [30]:
sc_stores[["Store ID", "Store Location", "Territory Manager", "Region"]]

    Store ID Store Location Territory Manager Region
98       852     Charleston        Len Jensen  South
99       853     Greenville        Len Jensen  South

# Core Marketing Analysis

## Question 1
Identify the territory managers, store IDs, and store locations for the assigned sales territories:
- Florida
- South Carolina

In [34]:
store_detail.columns

Index(['Store Location', 'State', 'Store ID', 'Territory Manager', 'Region',
       'Region Director'],
      dtype='object')

In [35]:
store_sales.columns

Index(['Transaction Date', 'Store ID', 'RewardsID', 'Prod Num', 'Sale Amount'], dtype='object')

## Question 2

Analyze the monthly total revenue for in-store sales in the assigned territories over the full period covered by the dataset.

In [4]:
store_sales["Transaction Date"] = pd.to_datetime(store_sales["Transaction Date"])

In [6]:
store_sales["Month"] = store_sales["Transaction Date"].dt.to_period("M")

In [11]:
sales_merged = pd.merge(store_sales, store_detail, on="Store ID")

In [12]:
sales_merged.head()

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Month,Store Location,State,Territory Manager,Region,Region Director
0,2022-01-01,702,NaN,105349-M,8.00,2022-01,Berthoud,Colorado,Jim Heck,West,Cassie Chambers
1,2022-01-01,704,NaN,105350-T,144.00,2022-01,Castle Rock,Colorado,Jim Heck,West,Cassie Chambers
2,2022-01-01,705,NaN,105351-M,44.00,2022-01,Denver,Colorado,Jim Heck,West,Cassie Chambers
3,2022-01-01,705,NaN,105352-M,47.61,2022-01,Denver,Colorado,Jim Heck,West,Cassie Chambers
4,2022-01-01,705,NaN,105353-A,20.36,2022-01,Denver,Colorado,Jim Heck,West,Cassie Chambers

In [13]:
florida_sales = sales_merged[sales_merged["State"] == "Florida"]

In [14]:
sc_sales = sales_merged[sales_merged["State"] == "South Carolina"]

In [15]:
florida_monthly_revenue = florida_sales.groupby("Month")["Sale Amount"].sum()

In [17]:
sc_monthly_revenue = sc_sales.groupby("Month")["Sale Amount"].sum()